'use strict';
const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');
const {chromium}=require(process.env.SPOKE_PLAYWRIGHT_MODULE||'playwright');
const axePath=process.env.SPOKE_AXE_PATH||require.resolve('axe-core/axe.min.js');
const executablePath=process.env.SPOKE_BROWSER_EXECUTABLE;const channel=process.env.SPOKE_BROWSER_CHANNEL;
const launchOptions={headless:true};if(executablePath)launchOptions.executablePath=executablePath;else if(channel)launchOptions.channel=channel;
const server=require('./server.cjs');const out=process.env.SPOKE_EVIDENCE_DIRECTORY||path.join(__dirname,'evidence');fs.mkdirSync(out,{recursive:true});const checks=[];const errors=[];const scans=[];const requests=[];
const result={started:new Date().toISOString(),checks,errors,scans,requests};const record=s=>checks.push(s);
async function axe(page,state){await page.addScriptTag({path:axePath});const r=await page.evaluate(async()=>await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','best-practice']}}));scans.push({state,violations:r.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)})),incomplete:r.incomplete.map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))});assert.equal(r.violations.length,0,JSON.stringify(scans.at(-1)));}
async function shot(p,name,fullPage=false){await p.screenshot({path:path.join(out,name+'.png'),fullPage});}
(async()=>{let browser;try{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}`;browser=await chromium.launch(launchOptions);result.browser={version:browser.version(),channel:executablePath?'custom-executable':channel||'playwright-chromium',...(executablePath?{executablePath}:{}),viewport:'1440x960, 768x1024, 390x844, 320x760',reducedMotion:'reduce'};const c=await browser.newContext({viewport:{width:1440,height:960},reducedMotion:'reduce'});await c.route('**/*',r=>{const u=new URL(r.request().url());if(u.hostname==='127.0.0.1')r.continue();else{requests.push(u.href);r.abort();}});const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(url);await p.locator('.hero-media img').evaluate(i=>i.decode());assert.equal(await p.locator('.hero-media img').evaluate(i=>i.naturalWidth),1600);record('Local repair photo loaded at natural width 1600px');await shot(p,'desktop-initial');await shot(p,'desktop-full',true);console.log('SCREENSHOTS_READY',path.join(out,'desktop-initial.png'));await axe(p,'desktop-initial');
await p.keyboard.press('Tab');assert.equal(await p.evaluate(()=>document.activeElement.textContent),'Skip to content');assert.equal(await p.locator('.skip-link').evaluate(e=>getComputedStyle(e).transform),'matrix(1, 0, 0, 1, 0, 0)');await shot(p,'keyboard-focus');await p.keyboard.press('Enter');assert.equal(await p.evaluate(()=>document.activeElement.id),'main');record('Keyboard first Tab shows skip link; Enter focuses main');
for(const width of [1440,768,390,320]){await p.setViewportSize({width,height:844});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`overflow ${width}`);record(`No page horizontal overflow at ${width}px`);}
await p.setViewportSize({width:390,height:844});await p.goto(url);await p.evaluate(()=>scrollTo(0,0));await shot(p,'mobile-initial');await shot(p,'mobile-full',true);console.log('MOBILE_READY',path.join(out,'mobile-initial.png'));await axe(p,'mobile-initial');
await p.getByRole('button',{name:'Choose Everyday tune',exact:true}).click();assert.equal(await p.locator('#service').inputValue(),'Everyday tune');assert.equal(await p.evaluate(()=>document.activeElement.id),'service');record('Service comparison Choose action prefills service and focuses service select');await shot(p,'mobile-form');
await p.locator('.submit').click();assert.equal(await p.evaluate(()=>document.activeElement.id),'error-summary');assert.equal(await p.locator('#error-list li').count(),3);assert.equal(await p.locator('#service').inputValue(),'Everyday tune');assert.equal(await p.title(),`Error: Spoke Workshop — Keep the good rides rolling`);await shot(p,'mobile-errors');await axe(p,'mobile-errors');await p.locator('#error-list a').first().click();assert.equal(await p.evaluate(()=>document.activeElement.id),'name');record('Empty form errors focus summary; links focus exact fields; prefilled service preserved');
await p.locator('#name').fill('Morgan Test');await p.locator('#email').fill('morgan@');await p.locator('#date').fill('2001-01-01');await p.locator('.submit').click();assert.equal(await p.locator('#email-error').textContent(),'Enter an email address like name@example.com.');assert.equal(await p.locator('#date-error').textContent(),'Choose today or a future date.');assert.equal(await p.locator('#name').inputValue(),'Morgan Test');record('Malformed email and past date yield specific errors and preserve name');
const date=new Date();date.setDate(date.getDate()+1);while(date.getDay()!==0)date.setDate(date.getDate()+1);const dateString=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;await p.locator('#email').fill('morgan@example.com');await p.locator('#date').fill(dateString(date));await p.locator('.submit').click();assert.equal(await p.locator('#date-error').textContent(),'Choose a Tuesday, Wednesday, Thursday, Friday, or Saturday.');record('Closed Sunday date rejected');date.setDate(date.getDate()+2);await p.locator('#date').fill(dateString(date));await p.locator('#notes').fill('City bike. Clicking under load. <img src=x onerror=alert(1)>');await p.locator('.submit').click();assert.equal(await p.evaluate(()=>document.activeElement.id),'request-preview');assert.equal(await p.locator('#request-preview').isVisible(),true);assert.equal(await p.locator('#preview-details img').count(),0);assert.equal(await p.locator('#preview-details').textContent().then(t=>t.includes('<img src=x onerror=alert(1)>')),true);assert.equal(await p.locator('#request-preview').textContent().then(t=>t.includes('No request has been sent')),true);await shot(p,'mobile-preview');await axe(p,'mobile-preview');record('Valid form produces honest local preview; safely displays literal notes and moves focus');
await p.locator('#edit-request').click();assert.equal(await p.evaluate(()=>document.activeElement.id),'name');assert.equal(await p.locator('#name').inputValue(),'Morgan Test');assert.equal(await p.locator('#service').inputValue(),'Everyday tune');record('Edit restores form, preserves submitted values, and focuses name');assert.equal(await p.evaluate(()=>getComputedStyle(document.documentElement).scrollBehavior),'auto');assert.equal(await p.locator('.button').first().evaluate(e=>getComputedStyle(e).transitionDuration),'0s');record('Reduced motion disables smooth scrolling and transitions');assert.equal(await p.evaluate(()=>localStorage.length+sessionStorage.length),0);assert.equal(requests.length,0);record('No external request and no web-storage write during local appointment flow');
await p.setViewportSize({width:1440,height:960});await p.locator('.submit').click();await shot(p,'desktop-preview');await p.locator('#edit-request').click();await p.locator('#email').fill('');await p.locator('.submit').click();await shot(p,'desktop-errors');await axe(p,'desktop-errors');await p.goto(url);await p.setViewportSize({width:390,height:844});await p.locator('#name').focus();const reached=[];for(let i=0;i<15;i++){const id=await p.evaluate(()=>document.activeElement.id||document.activeElement.className);if(id&&!reached.includes(id))reached.push(id);if(id==='button submit')break;await p.keyboard.press('Tab');}for(const id of ['name','email','service','date','notes'])assert(reached.includes(id));assert(reached.includes('button submit'));assert.equal(await p.locator('.submit').evaluate(e=>getComputedStyle(e).outlineWidth),'3px');await p.keyboard.press('Enter');assert.equal(await p.evaluate(()=>document.activeElement.id),'error-summary');await p.keyboard.press('Tab');await p.keyboard.press('Enter');assert.equal(await p.evaluate(()=>document.activeElement.id),'name');record('Keyboard traverses name, email, service, native date, notes and submit; visible submit focus; Enter submits and error-link Enter returns to name');await p.goto(url);await p.setViewportSize({width:768,height:1024});await shot(p,'tablet-initial');await p.setViewportSize({width:1440,height:960});await p.locator('#services').scrollIntoViewIfNeeded();await shot(p,'desktop-services');await p.locator('#approach').scrollIntoViewIfNeeded();await shot(p,'desktop-approach');await p.locator('#appointment').scrollIntoViewIfNeeded();await shot(p,'desktop-form');assert.equal(errors.length,0);record('No JavaScript page errors');result.status='passed';}catch(e){result.status='failed';result.failure=e.stack;console.error(e.stack);process.exitCode=1;}finally{result.finished=new Date().toISOString();fs.writeFileSync(path.join(out,'verification.json'),JSON.stringify(result,null,2));if(browser)await browser.close();await new Promise(r=>server.close(r));console.log(JSON.stringify(result,null,2));}})();



